# Generated by Django 3.1.5 on 2021-01-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', models.JSONField(null=True)),
                ('mean', models.FloatField(default=0.0, null=True)),
                ('variance', models.FloatField(default=1.0, null=True)),
                ('noise_type', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
