# Generated by Django 3.1.5 on 2021-01-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noise_signal', models.IntegerField(default=0)),
                ('variance', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
