# Generated by Django 3.1.5 on 2021-01-21 22:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210121_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noisemodel',
            name='noise_signal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None),
        ),
    ]
