# Generated by Django 3.1.5 on 2021-01-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210125_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noisemodel',
            name='array',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='variance',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
