# Generated by Django 3.1.5 on 2021-01-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210121_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noisemodel',
            name='signal',
        ),
    ]
