# Generated by Django 3.1.5 on 2021-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210126_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisemodel',
            name='mean',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='variance',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
