# Generated by Django 3.1.5 on 2021-01-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210126_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisemodel',
            name='noise_type',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
