# Generated by Django 3.1.5 on 2021-01-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_noisemodel_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='noisemodel',
            name='test',
            field=models.IntegerField(default=1),
        ),
    ]
