# Generated by Django 3.1.5 on 2021-01-21 22:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_noisemodel_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noisemodel',
            name='test',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), size=None),
        ),
    ]
