# Generated by Django 3.1.5 on 2021-01-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_noisemodel_noise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noisemodel',
            name='noise_type',
            field=models.CharField(default='', max_length=16),
        ),
    ]
